global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'air_quality_app'
    static_configs:
      - targets: ['frontend:5001']  # Adjust if your app is on a different host/port
    metrics_path: '/metrics'